name: sqlite3_async
description: "Provides a subset of async operations on top of sqlite3 package."
version: 1.0.8
repository: https://github.com/octavian-h/sqlite3-async

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  logging_appenders: ^2.0.0+1
  sqlite3: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
