name: sqlite3_async
description: "Provides a subset of async operations on top of sqlite3 Database class."
version: 1.0.7
repository: https://github.com/octavian-h/sqlite3-async

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  logging_appenders: ^1.3.1
  sqlite3: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqlite3_flutter_libs: ^0.5.26
